default: &default
  adapter: postgresql
  username: <%= Rails.application.credentials.user[:name] %>
  password: <%= Rails.application.credentials.user[:password] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: react_development

test:
  <<: *default
  database: react_test

production:
  <<: *default
  database: react_production
  username: react
  password: <%= ENV["BLOG_DATABASE_PASSWORD"] %>
